ShoeShop/Models/Brand.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace ProjectShoeShop.Models
{
    public class Brand
    {
        [Key]
        public string Id { get; set; }
        [Required]
        public string Name { get; set; }
        [Required]
        public string Description { get; set; }
    }
}

ShoeShop/Areas/Admin/Controllers/BrandController.cs
using ProjectShoeShop.DAL;
using ProjectShoeShop.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.UI;

namespace ProjectShoeShop.Areas.Admin.Controllers
{
    public class BrandController : Controller
    {
        // GET: Admin/Brand
        ShoeShopDbContext db = new ShoeShopDbContext();
        public ActionResult Index(String Search = "", String IconClass = "fa-sort-asc",
            String SortColumn = "Name", int Page = 1)
        {
            var listBrands = db.Brands.ToList();
            if(listBrands != null)
            {
                ViewBag.BrandsNumber = listBrands.Count;

                //Search
                if (!string.IsNullOrEmpty(Search))
                {
                    listBrands = db.Brands.Where(m => m.Name.Contains(Search)).ToList();
                    ViewBag.Search = Search;
                }

                //sort
                ViewBag.IconClass = IconClass;
                ViewBag.SortColumn = SortColumn;
                if (SortColumn == "Name")
                {
                    if (IconClass == "fa-sort-asc")
                    {
                        listBrands = listBrands.OrderBy(m => m.Name).ToList();
                    }
                    else
                    {
                        listBrands = listBrands.OrderByDescending(m => m.Name).ToList();
                    }
                }

                //Paging
                int NumberOfRecords = 7;
                int NumberOfPages = Convert.ToInt32(Math.Ceiling(listBrands.Count / (1.0 * NumberOfRecords)));
                int NumberOfRecordToSkip = (Page - 1) * NumberOfRecords;
                listBrands = listBrands.Skip(NumberOfRecordToSkip).Take(NumberOfRecords).ToList();
                ViewBag.NumberOfPages = NumberOfPages;
                ViewBag.Page = Page;

                return View(listBrands);
            }
            else
            {
                return HttpNotFound();
            }
        }

        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Create(Brand obj)
        {
            var brand = obj;
            if(brand != null)
            {
                if(db.Brands.Any(m => m.Name == brand.Name))
                {   
                    ViewBag.Message = "Tên đã tồn tại !";
                    return View();
                }
                brand.Id = Guid.NewGuid().ToString().Substring(0, 7);
                db.Brands.Add(brand);
                db.SaveChanges();
            }

            return RedirectToAction("Index");   
        }

        public ActionResult Edit(string id)
        {
            Brand brand = db.Brands.FirstOrDefault(x => x.Id == id);
            ViewBag.IdBrand = brand.Id;
            return View(brand); 
        }

        [HttpPost]
        public ActionResult Edit(Brand obj, string id)
        {
            var existingBrand = db.Brands.FirstOrDefault(x => x.Id == id);

            if (existingBrand != null)
            {
                if(db.Brands.Where(m => m.Id != id)
                            .Any(m => m.Name == obj.Name))
                {
                    ViewBag.Message = "Tên đã tồn tại !";
                    return View();
                }
                existingBrand.Name = obj.Name;
                existingBrand.Description = obj.Description;

                db.SaveChanges(); 
            }

            return RedirectToAction("Index");

        }

        public ActionResult Delete(string id)
        {
            var brand = db.Brands.FirstOrDefault(x => x.Id == id);

            return View(brand);
        }

        [HttpPost]
        [ActionName("Delete")]
        public ActionResult DeleteConfirm(string id)
        {
            var existingBrand = db.Brands.FirstOrDefault(x => x.Id == id);

            if (existingBrand != null)
            {
                db.Brands.Remove(existingBrand);

                db.SaveChanges();
            }

            return RedirectToAction("Index");

        }
    }
}

ShoeShop/Areas/Admin/Views/Brand/Create.cshtml
@model ProjectShoeShop.Models.Brand

@{
    ViewBag.Title = "Create";
    Layout = "~/Areas/Admin/Views/Shared/AdminLayoutPage1.cshtml";
}

<h2 class="title-page">Brands / @ViewBag.Title</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
<div class="form-horizontal">
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    @Html.HiddenFor(m => m.Id)
    <p class="text-danger">@ViewBag.Message</p>
    <div class="form-group">
        @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Create" class="btn btn-default" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

ShoeShop/Areas/Admin/Views/Brand/Delete.cshtml
@model ProjectShoeShop.Models.Brand

@{
    ViewBag.Title = "Delete";
    Layout = "~/Areas/Admin/Views/Shared/AdminLayoutPage1.cshtml";
}

<h2 class="title-page">Brands / @ViewBag.Title</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Brand</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

ShoeShop/Areas/Admin/Views/Brand/Edit.cshtml
@model ProjectShoeShop.Models.Brand

@{
    ViewBag.Title = "Edit";
    Layout = "~/Areas/Admin/Views/Shared/AdminLayoutPage1.cshtml";
}

<h2 class="title-page">Brands / @ViewBag.Title</h2>

@using (Html.BeginForm("Edit", "Brand", new {id=ViewBag.IdBrand}))
{
    @Html.AntiForgeryToken()
    
<div class="form-horizontal">
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    @Html.HiddenFor(model => model.Id)
    <p class="text-danger">@ViewBag.Message</p>
    <div class="form-group">
        @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Save" class="btn btn-default" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

ShoeShop/Areas/Admin/Views/Brand/Index.cshtml
@model IEnumerable<ProjectShoeShop.Models.Brand>

@{
    ViewBag.Title = "Index";
    Layout = "~/Areas/Admin/Views/Shared/AdminLayoutPage1.cshtml";
    var j = 1;

    string iconClass = "";
    if (ViewBag.IconClass == "fa-sort-asc")
    {
        iconClass = "fa-sort-desc";
    }
    else
    {
        iconClass = "fa-sort-asc";
    }

    string currentSortColumn = Request.QueryString["SortColumn"];
    string currentIconClass = Request.QueryString["IconClass"];
}

<h2 class="title-page">Brands</h2>

<div class="row" style="width: 101%;">
    <form style=" width: 25%;" action="/Admin/Brand/Index" class="col-3 form-search d-flex flex-row align-items-center">
        @Html.TextBox("Search", ViewBag.search as string, new
        {
            @class = "form-control w-auto mr-2",
            placeholder = "Search",
            type = "search"
        })
        <button type="submit" class="btn btn-primary"><i class="fa-solid fa-magnifying-glass"></i></button>
    </form>
    <p class="col" style="width: 120px; opacity: 0.8; align-self: center">@ViewBag.BrandsNumber records found</p>
    <p>
        <a class="btn btn-outline-success btn-add" href="/Admin/Brand/Create">Create New</a>
    </p>
</div>
<table class="table table-bordered text-center">
    <tr style="background-color: #576574">
        <th class="text-white">
            <a class="text-decoration-none text-white"
               href="/Admin/Brand/Index?SortColumn=Name&IconClass=@iconClass&Search=@ViewBag.search">
                Name
            </a>
            <i class="fa @ViewBag.IconClass"></i>
        </th>
        <th class="text-white">
            Description
        </th>
        <th class="text-white">
            Action
        </th>
    </tr>

@foreach (var item in Model) {
    <tr class="@(j == 2 ? "table-active" : "")">
        <td>
            @Html.DisplayFor(modelItem => item.Name)
        </td>
        <td>
            @if (item.Description.Length <= 100)
            {
                <p>@item.Description</p>
            }
            else
            {
                <p>@item.Description.Substring(0, 100)...</p>
            }
        </td>
        <td>
            <a class="btn btn-warning" href="/Admin/Brand/Edit?Id=@item.Id"><i class="fa-solid fa-pen-to-square"></i></a> |
            <a class="btn btn-danger" href="/Admin/Brand/Delete?Id=@item.Id"><i style="color: black" class="fa-solid fa-trash"></i></a>
        </td>
    </tr>
    j = j == 1 ? 2 : 1;
}

</table>
<tr>
    <td colspan="3">
        <ul class="pagination justify-content-center">
            @{
                int PrevPage = (ViewBag.Page - 1);
                int NextPage = (ViewBag.Page + 1);
                PrevPage = PrevPage <= 0 ? 1 : PrevPage;
                NextPage = NextPage > ViewBag.NumberOfPages ? ViewBag.NumberOfPages : NextPage;
            }
            <li class="page-item">
                <a class="page-link"
                   href="/Admin/Brand?Search=@ViewBag.search&Page=@PrevPage&SortColumn=@currentSortColumn&IconClass=@currentIconClass">Prev</a>
            </li>
            @for (int i = 1; i <= ViewBag.NumberOfPages; i++)
            {
                <li class="page-item">
                    <a class="page-link"
                       href="/Admin/Brand?Search=@ViewBag.search&Page=@i&SortColumn=@currentSortColumn&IconClass=@currentIconClass">@i</a>
                </li>
            }
            <li class="page-item">
                <a class="page-link"
                   href="/Admin/Brand?Search=@ViewBag.search&Page=@NextPage&SortColumn=@currentSortColumn&IconClass=@currentIconClass">Next</a>
            </li>
        </ul>
    </td>
</tr>