ShoeShop/Controllers/AboutController.cs
using ProjectShoeShop.DAL;
using ProjectShoeShop.Models;
using ProjectShoeShop.ViewModel;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ProjectShoeShop.Controllers
{
    public class AboutController : Controller
    {
        ShoeShopDbContext db = new ShoeShopDbContext();
        // GET: About
        public ActionResult AboutUs()
        {
            ViewBag.Random = GetRanDomReviews();

            return View();
        }
        public ActionResult AboutLayout()
        {
            return View();
        }
        public string GetRanDomReviews()
        {
            var random = db.Reviews.Where(t => t.Rating == 5).OrderBy(t => Guid.NewGuid()).Select(t => t.Comment).FirstOrDefault();
            return random;
        }
        public ActionResult ReviewPartial()
        {
            var lst = db.Reviews.Include(nameof(Review.User))
                    .Include(nameof(Review.Product)).Where(t => t.Rating == 5)
                    .Select(t => new ReviewVM
                    {
                        FullName = t.User.FullName,
                        ImagePath = t.User.ImagePath,
                        Comment = t.Comment,
                        Rating = t.Rating,
                        ReviewDate = t.ReviewDate
                    })
                    .ToList();
            if (lst != null)
            {
                return PartialView(lst);
            }
            else
            {
                return HttpNotFound();
            }
        }
    }
}

ShoeShop/Views/Shared/Footer.cshtml
<section class="ftco-gallery">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-8 heading-section text-center mb-4">
                <h2 class="mb-4">Follow Us On Instagram</h2>
                <p>Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts. Separated they live in</p>
            </div>
        </div>
    </div>
    <div class="container-fluid px-0">
        <div class="row no-gutters">
            <div class="col-md-4 col-lg-2">
                <a href="~/Assets/images/g-1.jpg" class="gallery image-popup img d-flex align-items-center" style="background-image: url(/Assets/images/g-1.jpg); ">
                    <div class="icon mb-4 d-flex align-items-center justify-content-center">
                        <span class="icon-instagram"></span>
                    </div>
                </a>
            </div>
            <div class="col-md-4 col-lg-2">
                <a href="~/Assets/images/g-2.jpg" class="gallery image-popup img d-flex align-items-center" style="background-image: url(/Assets/images/g-2.jpg);">
                    <div class="icon mb-4 d-flex align-items-center justify-content-center">
                        <span class="icon-instagram"></span>
                    </div>
                </a>
            </div>
            <div class="col-md-4 col-lg-2">
                <a href="~/Assets/images/g-3.jpg" class="gallery image-popup img d-flex align-items-center" style="background-image: url(/Assets/images/g-3.jpg);">
                    <div class="icon mb-4 d-flex align-items-center justify-content-center">
                        <span class="icon-instagram"></span>
                    </div>
                </a>
            </div>
            <div class="col-md-4 col-lg-2">
                <a href="~/Assets/images/g-4.jpg" class="gallery image-popup img d-flex align-items-center" style="background-image: url(/Assets/images/g-4.jpg);">
                    <div class="icon mb-4 d-flex align-items-center justify-content-center">
                        <span class="icon-instagram"></span>
                    </div>
                </a>
            </div>
            <div class="col-md-4 col-lg-2">
                <a href="~/Assets/images/g-5.jpg" class="gallery image-popup img d-flex align-items-center" style="background-image: url(/Assets/images/g-5.jpg);">
                    <div class="icon mb-4 d-flex align-items-center justify-content-center">
                        <span class="icon-instagram"></span>
                    </div>
                </a>
            </div>
            <div class="col-md-4 col-lg-2">
                <a href="~/Assets/images/g-6.jpg" class="gallery image-popup img d-flex align-items-center" style="background-image: url(/Assets/images/g-6.jpg);">
                    <div class="icon mb-4 d-flex align-items-center justify-content-center">
                        <span class="icon-instagram"></span>
                    </div>
                </a>
            </div>
        </div>
    </div>
</section>

<footer class="ftco-footer ftco-section">
    <div class="container">
        <div class="row">
            <div class="mouse">
                <a href="#" class="mouse-icon">
                    <div class="mouse-wheel"><span class="ion-ios-arrow-up"></span></div>
                </a>
            </div>
        </div>
        <div class="row mb-5">
            <div class="col-md">
                <div class="ftco-footer-widget mb-4">
                    <h2 class="ftco-heading-2">Minishop</h2>
                    <p>Far far away, behind the word mountains, far from the countries Vokalia and Consonantia.</p>
                    <ul class="ftco-footer-social list-unstyled float-md-left float-lft mt-5">
                        <li><a href="#"><span class="icon-twitter"></span></a></li>
                        <li><a href="#"><span class="icon-facebook"></span></a></li>
                        <li><a href="#"><span class="icon-instagram"></span></a></li>
                    </ul>
                </div>
            </div>
            <div class="col-md">
                <div class="ftco-footer-widget mb-4 ml-md-5">
                    <h2 class="ftco-heading-2">Menu</h2>
                    <ul class="list-unstyled">
                        <li><a href="#" class="py-2 d-block">Shop</a></li>
                        <li><a href="#" class="py-2 d-block">About</a></li>
                        <li><a href="#" class="py-2 d-block">Journal</a></li>
                        <li><a href="#" class="py-2 d-block">Contact Us</a></li>
                    </ul>
                </div>
            </div>
            <div class="col-md-4">
                <div class="ftco-footer-widget mb-4">
                    <h2 class="ftco-heading-2">Help</h2>
                    <div class="d-flex">
                        <ul class="list-unstyled mr-l-5 pr-l-3 mr-4">
                            <li><a href="#" class="py-2 d-block">Shipping Information</a></li>
                            <li><a href="#" class="py-2 d-block">Returns &amp; Exchange</a></li>
                            <li><a href="#" class="py-2 d-block">Terms &amp; Conditions</a></li>
                            <li><a href="#" class="py-2 d-block">Privacy Policy</a></li>
                        </ul>
                        <ul class="list-unstyled">
                            <li><a href="#" class="py-2 d-block">FAQs</a></li>
                            <li><a href="#" class="py-2 d-block">Contact</a></li>
                        </ul>
                    </div>
                </div>
            </div>
            <div class="col-md">
                <div class="ftco-footer-widget mb-4">
                    <h2 class="ftco-heading-2">Have a Questions?</h2>
                    <div class="block-23 mb-3">
                        <ul>
                            <li><span class="icon icon-map-marker"></span><span class="text">140, Lê Trọng Tấn, Tây Thạnh, Tân Phú, Việt Nam</span></li>
                            <li><a href="#"><span class="icon icon-phone"></span><span class="text">+2 392 3929 210</span></a></li>
                            <li><a href="#"><span class="icon icon-envelope"></span><span class="text">info@shop.com</span></a></li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-12 text-center">

                <p>
                    <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
                    Copyright &copy;
                    <script>document.write(new Date().getFullYear());</script>
                    <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
                </p>
            </div>
        </div>
    </div>
</footer>

ShoeShop/Views/Shared/FooterPage.cshtml
<footer class="ftco-footer ftco-section">
    <div class="container">
        <div class="row">
            <div class="mouse">
                <a href="#" class="mouse-icon">
                    <div class="mouse-wheel"><span class="ion-ios-arrow-up"></span></div>
                </a>
            </div>
        </div>
        <div class="row mb-5">
            <div class="col-md">
                <div class="ftco-footer-widget mb-4">
                    <h2 class="ftco-heading-2">Minishop</h2>
                    <p>Far far away, behind the word mountains, far from the countries Vokalia and Consonantia.</p>
                    <ul class="ftco-footer-social list-unstyled float-md-left float-lft mt-5">
                        <li><a href="#"><span class="icon-twitter"></span></a></li>
                        <li><a href="#"><span class="icon-facebook"></span></a></li>
                        <li><a href="#"><span class="icon-instagram"></span></a></li>
                    </ul>
                </div>
            </div>
            <div class="col-md">
                <div class="ftco-footer-widget mb-4 ml-md-5">
                    <h2 class="ftco-heading-2">Menu</h2>
                    <ul class="list-unstyled">
                        <li><a href="#" class="py-2 d-block">Shop</a></li>
                        <li><a href="#" class="py-2 d-block">About</a></li>
                        <li><a href="#" class="py-2 d-block">Journal</a></li>
                        <li><a href="#" class="py-2 d-block">Contact Us</a></li>
                    </ul>
                </div>
            </div>
            <div class="col-md-4">
                <div class="ftco-footer-widget mb-4">
                    <h2 class="ftco-heading-2">Help</h2>
                    <div class="d-flex">
                        <ul class="list-unstyled mr-l-5 pr-l-3 mr-4">
                            <li><a href="#" class="py-2 d-block">Shipping Information</a></li>
                            <li><a href="#" class="py-2 d-block">Returns &amp; Exchange</a></li>
                            <li><a href="#" class="py-2 d-block">Terms &amp; Conditions</a></li>
                            <li><a href="#" class="py-2 d-block">Privacy Policy</a></li>
                        </ul>
                        <ul class="list-unstyled">
                            <li><a href="#" class="py-2 d-block">FAQs</a></li>
                            <li><a href="#" class="py-2 d-block">Contact</a></li>
                        </ul>
                    </div>
                </div>
            </div>
            <div class="col-md">
                <div class="ftco-footer-widget mb-4">
                    <h2 class="ftco-heading-2">Have a Questions?</h2>
                    <div class="block-23 mb-3">
                        <ul>
                            <li><span class="icon icon-map-marker"></span><span class="text">203 Fake St. Mountain View, San Francisco, California, USA</span></li>
                            <li><a href="#"><span class="icon icon-phone"></span><span class="text">+2 392 3929 210</span></a></li>
                            <li><a href="#"><span class="icon icon-envelope"></span><span class="text">info@yourdomain.com</span></a></li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-12 text-center">

                <p>
                    <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
                    Copyright &copy;
                    <script>document.write(new Date().getFullYear());</script>
                    <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
                </p>
            </div>
        </div>
    </div>
</footer>

ShoeShop/Views/Shared/Header.cshtml
<div class="py-1 bg-black">
    <div class="container">
        <div class="row no-gutters d-flex align-items-start align-items-center px-md-0">
            <div class="col-lg-12 d-block">
                <div class="row d-flex">
                    <div class="col-md pr-4 d-flex topper align-items-center">
                        <div class="icon mr-2 d-flex justify-content-center align-items-center"><span class="icon-phone2"></span></div>
                        <span class="text">+ 1235 2355 98</span>
                    </div>
                    <div class="col-md pr-4 d-flex topper align-items-center">
                        <div class="icon mr-2 d-flex justify-content-center align-items-center"><span class="icon-paper-plane"></span></div>
                        <span class="text">thietbidientu@email.com</span>
                    </div>
                    <div class="col-md-5 pr-4 d-flex topper align-items-center text-lg-right">
                        <span class="text">3-5 Business days delivery &amp; Free Returns</span>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

ShoeShop/Views/Shared/Navbar.cshtml
@using ProjectShoeShop.Models

@{ 
    ProjectShoeShop.DAL.ShoeShopDbContext db = new ProjectShoeShop.DAL.ShoeShopDbContext();
    var product = db.Products.OrderBy(x => Guid.NewGuid()).FirstOrDefault();
} 

<nav class="navbar navbar-expand-lg navbar-dark ftco_navbar bg-dark ftco-navbar-light" id="ftco-navbar">
    <div class="container">
        <a class="navbar-brand" href="/Home/Index">Electronic Shop</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#ftco-nav" aria-controls="ftco-nav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="oi oi-menu"></span> Menu
        </button>

        <div class="collapse navbar-collapse" id="ftco-nav">
            <ul class="navbar-nav ml-auto">
                <li class="nav-item active"><a href="/Home/index" class="nav-link">Home</a></li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="dropdown04" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Catalog</a>
                    <div class="dropdown-menu" aria-labelledby="dropdown04">
                        <a class="dropdown-item" href="/Product/showProduct">Shop</a>
                        <a class="dropdown-item" href="/Product/DetailProduct?id=@product.Id&ProductName=@product.Name">Single Product</a>
                        <a class="dropdown-item" href="/Cart/ShowCart">Cart</a>
                    </div>
                </li>
                <li class="nav-item"><a href="@Url.Action("AboutUs", "About")" class="nav-link">About</a></li>
                <li class="nav-item"><a href="@Url.Action("ContactUs", "Contact")" class="nav-link">Contact</a></li>
                <li class="nav-item align-self-center cta cta-colored dropdown" style="width: 100%;">
                    <div class="row">
                        @Html.Action("AccountPartialView", "Account")
                    </div>
                </li>
                <li class="nav-item cta cta-colored">
                    @Html.Action("CartPartial", "Cart")
                </li>

            </ul>
        </div>
    </div>
</nav>

ShoeShop/Views/Shared/ShoeShop.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Electronic shop - Buy it all at the store</title>
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,400,600,700,800" rel="stylesheet">

    <link rel="stylesheet" href="~/Assets/css/open-iconic-bootstrap.min.css">
    <link rel="stylesheet" href="css/animate.css">

    <link rel="stylesheet" href="~/Assets/css/owl.carousel.min.css">
    <link rel="stylesheet" href="~/Assets/css/owl.theme.default.min.css">
    <link rel="stylesheet" href="~/Assets/css/magnific-popup.css">

    <link rel="stylesheet" href="~/Assets/css/aos.css">

    <link rel="stylesheet" href="~/Assets/css/ionicons.min.css">

    <link rel="stylesheet" href="~/Assets/css/bootstrap-datepicker.css">
    <link rel="stylesheet" href="~/Assets/css/jquery.timepicker.css">


    <link rel="stylesheet" href="~/Assets/css/flaticon.css">
    <link rel="stylesheet" href="~/Assets/css/icomoon.css">
    <link rel="stylesheet" href="~/Assets/css/style.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css" integrity="sha512-DTOQO9RWCH3ppGqcWaEA1BIZOC6xxalwEsw9c2QQeAIftl+Vegovlnee1c9QX4TctnWMn13TZye+giMm8e2LwA==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/sweetalert2@11/dist/sweetalert2.min.css">
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
</head>
<body class="" goto-here">
    @RenderPage("~/Views/Shared/Header.cshtml")
    @RenderPage("~/Views/Shared/Navbar.cshtml")
    @*@RenderPage("~/Views/Shared/Slide.cshtml")*@
    @RenderSection("about", required: false)
    @RenderSection("cart", required: false)
    @RenderBody()
    @RenderPage("~/Views/Shared/Footer.cshtml")

    <div id="ftco-loader" class="show fullscreen"><svg class="circular" width="48px" height="48px"><circle class="path-bg" cx="24" cy="24" r="22" fill="none" stroke-width="4" stroke="#eeeeee" /><circle class="path" cx="24" cy="24" r="22" fill="none" stroke-width="4" stroke-miterlimit="10" stroke="#F96D00" /></svg></div>

    @if (TempData["OutOfStockMessage"] != null)
    {
        var notification = @TempData["OutOfStockMessage"] as string;

        <script>
        Swal.fire({
            icon: 'error',
            title: 'Error',
            text: '@Html.Raw(notification)',
            confirmButtonText: 'OK'
        });
        </script>
    }

    <script src="~/Assets/js/jquery.min.js"></script>
    <script src="~/Assets/js/jquery-migrate-3.0.1.min.js"></script>
    <script src="~/Assets/js/popper.min.js"></script>
    <script src="~/Assets/js/bootstrap.min.js"></script>
    <script src="~/Assets/js/jquery.easing.1.3.js"></script>
    <script src="~/Assets/js/jquery.waypoints.min.js"></script>
    <script src="~/Assets/js/jquery.stellar.min.js"></script>
    <script src="~/Assets/js/owl.carousel.min.js"></script>
    <script src="~/Assets/js/jquery.magnific-popup.min.js"></script>
    <script src="~/Assets/js/aos.js"></script>
    <script src="~/Assets/js/jquery.animateNumber.min.js"></script>
    <script src="~/Assets/js/bootstrap-datepicker.js"></script>
    <script src="~/Assets/js/scrollax.min.js"></script>
    <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBVWaKrjvy3MaE7SQ74_uJiULgl1JY0H2s&sensor=false"></script>
    <script src="~/Assets/js/google-map.js"></script>
    <script src="~/Assets/js/main.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11/dist/sweetalert2.all.min.js"></script>
</body>
</html>

ShoeShop/Views/Shared/ShoeShopPage.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Electronic shop - Buy it all at the store</title>
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,400,600,700,800" rel="stylesheet">

    <link rel="stylesheet" href="~/Assets/css/open-iconic-bootstrap.min.css">
    <link rel="stylesheet" href="css/animate.css">

    <link rel="stylesheet" href="~/Assets/css/owl.carousel.min.css">
    <link rel="stylesheet" href="~/Assets/css/owl.theme.default.min.css">
    <link rel="stylesheet" href="~/Assets/css/magnific-popup.css">

    <link rel="stylesheet" href="~/Assets/css/aos.css">

    <link rel="stylesheet" href="~/Assets/css/ionicons.min.css">

    <link rel="stylesheet" href="~/Assets/css/bootstrap-datepicker.css">
    <link rel="stylesheet" href="~/Assets/css/jquery.timepicker.css">


    <link rel="stylesheet" href="~/Assets/css/flaticon.css">
    <link rel="stylesheet" href="~/Assets/css/icomoon.css">
    <link rel="stylesheet" href="~/Assets/css/style.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css" integrity="sha512-DTOQO9RWCH3ppGqcWaEA1BIZOC6xxalwEsw9c2QQeAIftl+Vegovlnee1c9QX4TctnWMn13TZye+giMm8e2LwA==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/sweetalert2@11/dist/sweetalert2.min.css">
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
</head>
<body class="" goto-here">
    @RenderPage("~/Views/Shared/Header.cshtml")
    @RenderPage("~/Views/Shared/Navbar.cshtml")
    @*@RenderPage("~/Views/Shared/Slide.cshtml")*@
    @RenderSection("about", required: false)
    @RenderSection("cart", required: false)
    @RenderBody()
    @RenderPage("~/Views/Shared/FooterPage.cshtml")

    <div id="ftco-loader" class="show fullscreen"><svg class="circular" width="48px" height="48px"><circle class="path-bg" cx="24" cy="24" r="22" fill="none" stroke-width="4" stroke="#eeeeee" /><circle class="path" cx="24" cy="24" r="22" fill="none" stroke-width="4" stroke-miterlimit="10" stroke="#F96D00" /></svg></div>

    @if (TempData["OutOfStockMessage"] != null)
    {
        var notification = @TempData["OutOfStockMessage"] as string;

        <script>
            Swal.fire({
                icon: 'error',
                title: 'Error',
                text: '@Html.Raw(notification)',
                confirmButtonText: 'OK'
            });
        </script>
    }

    <script src="~/Assets/js/jquery.min.js"></script>
    <script src="~/Assets/js/jquery-migrate-3.0.1.min.js"></script>
    <script src="~/Assets/js/popper.min.js"></script>
    <script src="~/Assets/js/bootstrap.min.js"></script>
    <script src="~/Assets/js/jquery.easing.1.3.js"></script>
    <script src="~/Assets/js/jquery.waypoints.min.js"></script>
    <script src="~/Assets/js/jquery.stellar.min.js"></script>
    <script src="~/Assets/js/owl.carousel.min.js"></script>
    <script src="~/Assets/js/jquery.magnific-popup.min.js"></script>
    <script src="~/Assets/js/aos.js"></script>
    <script src="~/Assets/js/jquery.animateNumber.min.js"></script>
    <script src="~/Assets/js/bootstrap-datepicker.js"></script>
    <script src="~/Assets/js/scrollax.min.js"></script>
    <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBVWaKrjvy3MaE7SQ74_uJiULgl1JY0H2s&sensor=false"></script>
    <script src="~/Assets/js/google-map.js"></script>
    <script src="~/Assets/js/main.js"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11/dist/sweetalert2.all.min.js"></script>
</body>
</html>

ShoeShop/Views/Shared/Slide.cshtml
<section id="home-section" class="hero">
    <div class="home-slider owl-carousel">
        <div class="slider-item">
            <div class="overlay"></div>
            <div class="container-fluid p-0">
                <div class="row d-md-flex no-gutters slider-text align-items-center justify-content-end" data-scrollax-parent="true">
                    <img class="one-third order-md-last img-fluid" src="~/Assets/images/p1.png" alt="">
                    <div class="one-forth d-flex align-items-centere">
                        <div class="text">
                            <span class="subheading">#New Arrival</span>
                            <div class="horizontal">
                                <h1 class="mb-4 mt-3">Computer And Mobile</h1>
                                <p class="mb-4">Explore our latest collection of computers, laptops, and smartphones. We offer top-quality products from leading brands to meet all your tech needs.</p>

                                <p><a href="#" class="btn-custom">Discover Now</a></p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <div class="slider-item">
            <div class="overlay"></div>
            <div class="container-fluid p-0">
                <div class="row d-flex no-gutters slider-text align-items-center justify-content-end" data-scrollax-parent="true">
                    <img class="one-third order-md-last img-fluid w-50" src="~/Assets/images/p2.png" alt="">
                    <div class="one-forth d-flex align-items-center">
                        <div class="text">
                            <span class="subheading">#New Arrival</span>
                            <div class="horizontal">
                                <h1 class="mb-4 mt-3">New Gaming Computer 2024</h1>
                                <p class="mb-4">Discover the power and performance of our latest Gaming Computer for 2024. Equipped with cutting-edge hardware, fast processing speeds, and immersive graphics, this machine is designed to elevate your gaming experience to the next level.</p>

                                <p><a href="#" class="btn-custom">Discover Now</a></p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>